### ISSUE TITLE
python -m demo.qa gives code error

### ISSUE THREAD

**Issue by wel3kxial** [vinhkhuc/MemN2N-babi-python#12]
oitai@ours:~/tk/chat/MemN2N-babi-python$ python -m demo.qa
Loading model from file trained_model/memn2n_model.pklz ...
Traceback (most recent call last):
  File "/home/ai/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ai/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ai/tk/chat/MemN2N-babi-python/demo/qa.py", line 268, in <module>
    run_web_demo(args.data_dir, args.model_file)
  File "/home/ai/tk/chat/MemN2N-babi-python/demo/qa.py", line 241, in run_web_demo
    webapp.init(data_dir, model_file)
  File "/home/ai/tk/chat/MemN2N-babi-python/demo/web/webapp.py", line 22, in init
    memn2n.load_model()
  File "/home/ai/tk/chat/MemN2N-babi-python/demo/qa.py", line 43, in load_model
    self.reversed_dict, self.memory, self.model, self.loss, self.general_config = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 0: ordinal not in range(128)

**Comment by vinayakpahalwan7** [comment]
Try changing this line :
`self.reversed_dict, self.memory, self.model, self.loss, self.general_config = pickle.load(f)`

to this:
`self.reversed_dict, self.memory, self.model, self.loss, self.general_config = pickle.load(f, encoding='bytes')`
